name: qtl_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pyyaml>=6.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.13.0
  - plotly>=5.0.0
  - pytorch>=1.9.0
  - pyarrow>=3.0.0
  - pandas-plink>=2.0.0
  - pip
  - pip:
    - tensorqtl>=1.0.8