name: qtl-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pyyaml>=6.0
  - statsmodels>=0.13.0
  - scikit-learn>=1.0.0
  - jinja2>=3.0.0
  - qtltools>=1.3.1
  - bcftools>=1.14
  - plink>=1.9
  - htslib>=1.14  # provides bgzip, tabix
  - pip
  - pip:
    - --no-deps