# QTL Analysis Pipeline - Complete Production Configuration
# Enhanced with normalization pipeline and batch correction
# Author: Dr. Vijay Singh
# Email: vijay.s.gautam@gmail.com
# Version: 2.0

# ==============================================
# MANDATORY: Core Configuration
# ==============================================

# Results directory where all output will be stored
results_dir: "/home/ubuntu/DATA_DRIVE/qtl_analysis/results"

# Input files section
input_files:
  # Genotype file - supports VCF, VCF.GZ, BCF, PLINK BED formats
  genotypes: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/genotypes.vcf.gz"
  
  # Covariates file (tab-separated)
  covariates: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/covariates.txt"
  
  # Annotation file (BED format)
  annotations: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/annotations.bed"
  
  # Phenotype files
  expression: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/expression.tsv"
  protein: "" # "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/protein.tsv"
  splicing: "" #"/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/splicing.tsv"

  # Confounders files for batch correction
  rnaseq_confounders: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/rnaseq_confounders.tsv"
  protein_confounders: "" #"/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/protein_confounders.tsv"

# ==============================================
# Enhanced Pipeline Configuration
# ==============================================

enhanced_pipeline:
  # Enable the enhanced normalization pipeline with batch correction
  enable: true
  
  # Generate comprehensive comparison plots
  generate_comparison_plots: true
  
  # Types of comparisons to generate
  comparison_types: 
    - "raw_vs_normalized"
    - "normalized_vs_corrected"
  
  # Performance settings
  parallel_processing: true
  max_memory_gb: 16
  
  # Output structure settings
  force_consistent_structure: true
  create_all_qtl_directories: true

# ==============================================
# Batch Correction Configuration
# ==============================================

batch_correction:
  # Enable/disable batch correction per QTL type
  enabled:
    eqtl: true
    pqtl: true  
    sqtl: false  # Typically not needed for splicing data
  
  # Column names for batch effects in confounders file
  batch_columns:
    eqtl: ["RNASeq_Batch", "Sequencing_Run"]
    pqtl: ["Protein_Batch", "Sample_Plate"]  # Fallback to RNASeq_Batch if not available
    sqtl: []  # Empty for splicing
  
  # Column names for covariates in confounders file
  covariate_columns:
    eqtl: ["Age", "Sex", "RNASeq_RIN", "PMI", "Ischemic_Time"]
    pqtl: ["Age", "Sex", "BMI"]  # Fewer covariates for protein data
    sqtl: ["Age", "Sex"]  # Minimal covariates for splicing
  
  # Method-specific settings
  method: "linear_regression"  # "linear_regression", "combat", "limma"
  apply_to: "all"  # "all", "significant_only", "variable_features"
  
  # Output settings
  force_corrected_files: true  # Always create corrected files even if no correction applied

# ==============================================
# Normalization Configuration
# ==============================================

normalization:
  # eQTL normalization options
  eqtl:
    method: "vst"  # "vst", "log2", "quantile", "tpm", "raw"
    vst_blind: true
    fit_type: "parametric"
    use_deseq2: true
    filtering:
      min_non_zero_samples: 0.2
      max_zero_samples: 0.8
    
  # pQTL normalization options  
  pqtl:
    method: "log2"  # "log2", "quantile", "zscore", "raw"
    log2_pseudocount: 1
    remove_zeros: true
    filtering:
      min_non_zero_samples: 0.1
      max_zero_samples: 0.9
    
  # sQTL normalization options
  sqtl:
    method: "log2"  # "log2", "arcsinh", "zscore", "raw"
    log2_pseudocount: 1
    psi_range: [0, 1]  # PSI values range
    filtering:
      min_non_zero_samples: 0.15
      max_zero_samples: 0.85
    
  # Global normalization settings
  global:
    remove_constant_features: true
    constant_threshold: 0.95
    missing_value_threshold: 0.2
    save_intermediate: true

# ==============================================
# Output Structure Configuration
# ==============================================

output_structure:
  # Required directories (always created)
  required_directories:
    - "normalization_comparison"
    - "normalization_comparison/eqtl"
    - "normalization_comparison/pqtl"
    - "normalization_comparison/sqtl"
    - "normalization_comparison/batch_correction"
    - "normalization"
    - "normalization/temp_normalization"
    - "batch_corrected"
    - "logs"
  
  # File naming patterns (consistent across all QTL types)
  file_patterns:
    raw_data: "{qtl_type}_raw_data.tsv"
    normalized: "{qtl_type}.normalised.{method}.tsv"
    corrected: "{qtl_type}.normalised.{method}.corrected.tsv"
    comparison_report: "{qtl_type}_normalization_report.html"
    statistical_summary: "{qtl_type}_statistical_summary.txt"
    pipeline_summary: "{qtl_type}_enhanced_pipeline_summary.yaml"
    correction_info: "correction_info.yaml"
  
  # File formats and compression
  compression: true
  compression_level: 6
  remove_intermediate: false

# ==============================================
# Performance and Resource Configuration
# ==============================================

performance:
  # System resources
  num_threads: 8
  memory_gb: 52
  max_workers: 8
  
  # Enhanced pipeline performance
  max_comparison_samples: 1000
  max_comparison_features: 100
  parallel_comparison: true
  
  # R script performance
  r_memory_gb: 16
  r_num_threads: 4
  
  # Temporary directory settings
  temp_dir: "temp"
  cleanup_temp: true
  cache_intermediate: true
  
  # Multi-processing settings
  process_by_chromosome: true
  chromosome_batch_size: 4

# ==============================================
# tensorQTL Configuration
# ==============================================

tensorqtl:
  # Basic parameters
  cis_window: 1000000
  maf_threshold: 0.05
  min_maf: 0.01
  fdr_threshold: 0.05
  
  # Performance settings
  use_gpu: false
  batch_size: 20000
  chunk_size: 200
  num_permutations: 1000
  
  # Statistical methods
  run_permutations: true
  run_eigenmt: false
  seed: 12345
  
  # Output options
  write_stats: true
  write_top_results: true
  output_format: "parquet"
  write_sparse: true
  
  # Advanced options
  impute_missing: true
  center_features: true
  standardize_features: true
  
  # Interaction analysis
  interaction_method: "linear"
  
  # Fine-mapping
  finemap_method: "susie"

# ==============================================
# Analysis Configuration
# ==============================================

analysis:
  # QTL analysis types
  qtl_types: "all"  # "all", "eqtl", "pqtl", "sqtl" or comma-separated list
  
  # QTL mapping mode
  qtl_mode: "cis"  # "cis", "trans", "both"
  
  # GWAS analysis
  run_gwas: false
  gwas_phenotype: ""

# ==============================================
# Quality Control Configuration
# ==============================================

qc:
  # Sample QC
  check_sample_concordance: true
  sample_missingness_threshold: 0.1
  sample_heterozygosity_threshold: 3
  
  # Variant QC
  check_maf_distribution: true
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6
  
  # Expression data filtering
  filter_low_expressed: true
  expression_threshold: 0.1
  normalize: true
  check_missingness: true
  
  # Expression data filtering based on QTL best practices
  filter_lowly_expressed_genes: true
  low_expression_threshold: 0.1
  max_low_expression_samples_percentage: 10

# ==============================================
# Enhanced QC Configuration
# ==============================================

enhanced_qc:
  enable: true
  generate_normalization_plots: true 
  sample_missingness_threshold: 0.1
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6
  maf_threshold: 0.01
  run_pca: true
  num_pcs: 10
  batch_effect_correction: true
  expression_normalization: true
  outlier_detection: true
  
  # PCA options for covariates
  pca_covariates: true
  num_pc_covariates: 5

# ==============================================
# Plotting Configuration
# ==============================================

plotting:
  enabled: true
  dpi: 300
  format: "png"
  style: "seaborn"
  
  # Color scheme
  colors:
    primary: "#2E86AB"
    secondary: "#A23B72"
    significant: "#F18F01"
    nonsignificant: "#C5C5C5"
    success: "#28a745"
    warning: "#ffc107"
    danger: "#dc3545"
  
  # Plot types
  plot_types:
    - "manhattan"
    - "qq"
    - "volcano"
    - "distribution"
    - "summary"
    - "locuszoom"
    - "heatmap"
    - "pca"
    - "correlation"
  
  # Figure sizes
  figure_sizes:
    small: [8, 6]
    medium: [12, 8]
    large: [15, 10]
    xlarge: [18, 12]

# ==============================================
# Output and Reporting Configuration
# ==============================================

output:
  # General output settings
  compression: true
  remove_intermediate: false
  generate_report: true
  report_format: "html"
  save_plots: true
  create_summary: true
  interactive_reports: true
  generate_methods_section: true
  
  # Enhanced pipeline output
  save_normalized: true
  save_corrected: true
  normalized_suffix: "normalised.{method}.tsv"
  corrected_suffix: "normalised.{method}.corrected.tsv"
  
  # tensorQTL output options
  save_nominal: true
  save_permutations: true
  save_interactions: false
  save_conditional: false
  
  # File formats
  phenotype_format: "parquet"  # "parquet", "csv"
  result_format: "parquet"     # "parquet", "csv"

# ==============================================
# Paths to Tools and Scripts
# ==============================================

paths:
  # Primary analysis tool (tensorQTL)
  tensorqtl: "python"   # tensorQTL is a Python package
  
  # Legacy tool (for reference)
  qtltools: "QTLtools"
  
  # Supporting tools
  bcftools: "bcftools"
  bgzip: "bgzip"
  tabix: "tabix"
  python: "python3"
  plink: "plink"
  R: "R"
  
  # R scripts
  r_script_deseq2: "scripts/deseq2_vst.R"
  r_script_normalization: "scripts/normalization_pipeline.R"
  
  # Python scripts
  normalization_comparison: "scripts/normalization_comparison.py"
  batch_correction: "scripts/batch_correction.py"
  enhanced_pipeline: "scripts/enhanced_comparison_pipeline.py"

# ==============================================
# Advanced and Experimental Settings
# ==============================================

advanced:
  # Debug and logging
  debug_mode: false
  save_logs: true
  log_level: "INFO"  # "DEBUG", "INFO", "WARNING", "ERROR"
  validate_outputs: true
  strict_mode: true
  benchmark: true
  
  # Enhanced pipeline options
  enable_enhanced_pipeline: true
  fallback_to_standard: true  # Fall back to standard if enhanced fails
  validate_r_scripts: true
  
  # tensorQTL advanced options
  tensorqtl_debug: false
  dry_run: false
  resume: false
  
  # Data handling
  use_dask: false  # For very large datasets
  cache_intermediate: true
  compression_level: 6
  
  # Statistical options
  adjust_for_genomic_inflation: true
  store_full_results: false
  
  # Experimental features
  enable_experimental: false
  test_new_normalization: false
  enable_custom_filters: false

# ==============================================
# Large Dataset Configuration
# ==============================================

large_data:
  # Resource requirements
  min_memory_gb: 32
  min_disk_gb: 100
  command_timeout: 10800  # 3 hours for larger datasets
  
  # Processing strategies
  process_by_chromosome: true
  force_plink: true
  monitor_resources: true
  cache_intermediate: true
  max_concurrent_chromosomes: 4
  
  # Chunking settings
  genotype_chunk_size: 10000
  phenotype_chunk_size: 500
  correlation_chunk_size: 1000

# ==============================================
# Email and Notification Settings
# ==============================================

notifications:
  enable_email: false
  email_server: "smtp.gmail.com"
  email_port: 587
  email_sender: "your_email@gmail.com"
  email_recipients:
    - "recipient1@example.com"
    - "recipient2@example.com"
  
  # Notification triggers
  notify_on_start: true
  notify_on_completion: true
  notify_on_error: true
  notify_on_warning: false

# ==============================================
# Version and Metadata
# ==============================================

metadata:
  pipeline_name: "Enhanced QTL Analysis Pipeline"
  version: "2.0"
  author: "Dr. Vijay Singh"
  contact: "vijay.s.gautam@gmail.com"
  description: "Comprehensive QTL analysis pipeline with enhanced normalization and batch correction"
  created: "2024-01-15"
  last_updated: "2024-01-15"
  
  # Dependencies
  dependencies:
    python: ">=3.8"
    tensorqtl: ">=1.0.8"
    pandas: ">=1.3.0"
    numpy: ">=1.21.0"
    matplotlib: ">=3.4.0"
    seaborn: ">=0.11.0"
    plotly: ">=5.3.0"
    scipy: ">=1.7.0"
    scikit-learn: ">=1.0.0"
    R: ">=4.0.0"
    DESeq2: ">=1.30.0"