# QTL Analysis Pipeline - Complete Production Configuration
# Enhanced with normalization pipeline and batch correction
# Author: Dr. Vijay Singh
# Email: vijay.s.gautam@gmail.com
# Version: 2.0

# ==============================================
# MANDATORY: Core Configuration
# ==============================================

# Results directory where all output will be stored
results_dir: "/home/ubuntu/DATA_DRIVE/qtl_analysis/results"

# Input files section
input_files:
  # Genotype file - supports VCF, VCF.GZ, BCF, PLINK BED formats
  genotypes: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/genotypes.vcf.gz"
  
  # Covariates file (tab-separated)
  covariates: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/covariates.txt"
  
  # Annotation file (BED format)
  annotations: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/annotations.bed"
  
  # Phenotype files
  expression: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/expression.tsv"

  # Confounders files for batch correction
  confounders: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data/confounders.tsv" # based on data

# ==============================================
# Enhanced Pipeline Configuration
# ==============================================

enhanced_pipeline:
  # Enable the enhanced normalization pipeline with batch correction
  enable: true
  
  # Generate comprehensive comparison plots
  generate_comparison_plots: true
  
  # Types of comparisons to generate
  comparison_types: 
    - "raw_vs_normalized"
    - "normalized_vs_corrected"
  
  # Performance settings
  parallel_processing: true
  max_memory_gb: 16
  
  # Output structure settings
  force_consistent_structure: true
  create_all_qtl_directories: true

# ==============================================
# Batch Correction Configuration
# ==============================================

batch_correction:
  # Enable/disable batch correction per QTL type
  enabled: true
  
  # Column names for batch effects in confounders file
  orce_corrected_files: true
  confounder_factor_columns: ["RNASeq_Batch", "Sex"] # If not required then will be either None or ""
  confounder_lineaer_columns: ["Age", "RNASeq_RIN"]
  

# ==============================================
# Analysis Configuration
# ==============================================

analysis:
  # QTL analysis types
  qtl_types: "eqtl"  # "eqtl", "pqtl", "sqtl" one at a time
  
  # QTL mapping mode
  qtl_mode: "cis"  # "cis", "trans", "both"
  
  # GWAS analysis
  run_gwas: false
  gwas_phenotype: ""

# ==============================================
# Normalization Configuration
# ==============================================
analysis_type: "eqtl"
normalization:
  # eQTL normalization options
  eqtl:
    method: "vst"  # "vst", "log2", "quantile", "tpm", "raw"
    vst_blind: true
    fit_type: "parametric"
    use_deseq2: true
    filtering:
      min_non_zero_samples: 0.2
      max_zero_samples: 0.8
    
  # pQTL normalization options  
  pqtl:
    method: "log2"  # "log2", "quantile", "zscore", "raw"
    log2_pseudocount: 1
    remove_zeros: true
    filtering:
      min_non_zero_samples: 0.1
      max_zero_samples: 0.9
    
  # sQTL normalization options
  sqtl:
    method: "log2"  # "log2", "arcsinh", "zscore", "raw"
    log2_pseudocount: 1
    psi_range: [0, 1]  # PSI values range
    filtering:
      min_non_zero_samples: 0.15
      max_zero_samples: 0.85
    

# ==============================================
# Performance and Resource Configuration
# ==============================================

performance:
  # System resources
  num_threads: 8
  memory_gb: 52
  max_workers: 8
  
  # Enhanced pipeline performance
  max_comparison_samples: 1000
  max_comparison_features: 100
  parallel_comparison: true
  
  # R script performance
  r_memory_gb: 16
  r_num_threads: 4
  
  # Temporary directory settings
  temp_dir: "temp"
  cleanup_temp: true
  cache_intermediate: true
  
  # Multi-processing settings
  process_by_chromosome: true
  chromosome_batch_size: 4

# ==============================================
# tensorQTL Configuration
# ==============================================

tensorqtl:
  # Basic parameters
  cis_window: 1000000
  maf_threshold: 0.05
  min_maf: 0.01
  fdr_threshold: 0.05
  
  # Performance settings
  use_gpu: false
  batch_size: 20000
  chunk_size: 200
  num_permutations: 1000
  
  # Statistical methods
  run_permutations: true
  run_eigenmt: false
  seed: 12345
  
  # Output options
  write_stats: true
  write_top_results: true
  output_format: "parquet"
  write_sparse: true
  
  # Advanced options
  impute_missing: true
  center_features: true
  standardize_features: true
  
  # Interaction analysis
  interaction_method: "linear"
  
  # Fine-mapping
  finemap_method: "susie"


# ==============================================
# Quality Control Configuration
# ==============================================

qc:
  # Sample QC
  check_sample_concordance: true
  sample_missingness_threshold: 0.1
  sample_heterozygosity_threshold: 3
  
  # Variant QC
  check_maf_distribution: true
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6
  
  # Expression data filtering
  filter_low_expressed: true
  expression_threshold: 0.1
  normalize: true
  check_missingness: true
  
  # Expression data filtering based on QTL best practices
  filter_lowly_expressed_genes: true
  low_expression_threshold: 0.1
  max_low_expression_samples_percentage: 10

# ==============================================
# Enhanced QC Configuration
# ==============================================

enhanced_qc:
  enable: true
  generate_normalization_plots: true 
  sample_missingness_threshold: 0.1
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6
  maf_threshold: 0.01
  run_pca: true
  num_pcs: 10
  batch_effect_correction: true
  expression_normalization: true
  outlier_detection: true
  
  # PCA options for covariates
  pca_covariates: true
  num_pc_covariates: 5

# ==============================================
# Plotting Configuration
# ==============================================

plotting:
  enabled: true
  dpi: 300
  format: "png"
  style: "seaborn"
  
  # Color scheme
  colors:
    primary: "#2E86AB"
    secondary: "#A23B72"
    significant: "#F18F01"
    nonsignificant: "#C5C5C5"
    success: "#28a745"
    warning: "#ffc107"
    danger: "#dc3545"
  
  # Figure sizes
  figure_sizes:
    small: [8, 6]
    medium: [12, 8]
    large: [15, 10]
    xlarge: [18, 12]

# ==============================================
# Output and Reporting Configuration
# ==============================================

output:
  # General output settings
  compression: true
  remove_intermediate: false
  generate_report: true
  report_format: "html"
  save_plots: true
  create_summary: true
  interactive_reports: true
  generate_methods_section: true
  
  # Enhanced pipeline output
  save_normalized: true
  save_corrected: true
  normalized_suffix: "normalised.{method}.tsv"
  corrected_suffix: "normalised.{method}.corrected.tsv"
  
  # tensorQTL output options
  save_nominal: true
  save_permutations: true
  save_interactions: false
  save_conditional: false
  
  # File formats
  phenotype_format: "parquet"  # "parquet", "csv"
  result_format: "parquet"     # "parquet", "csv"

# ==============================================
# Large Dataset Configuration
# ==============================================

large_data:
  # Resource requirements
  min_memory_gb: 32
  min_disk_gb: 100
  command_timeout: 10800  # 3 hours for larger datasets
  
  # Processing strategies
  process_by_chromosome: true
  force_plink: true
  monitor_resources: true
  cache_intermediate: true
  max_concurrent_chromosomes: 4
  
  # Chunking settings
  genotype_chunk_size: 10000
  phenotype_chunk_size: 500
  correlation_chunk_size: 1000
