# QTL Analysis Pipeline - Complete Configuration
# Optimized for QTLtools with proper normalization strategies
# ==============================================

# MANDATORY: Results directory where all output will be stored
results_dir: "results"

# MANDATORY: Input files section
input_files:
  # Genotype file - supports VCF, VCF.GZ, BCF, PLINK BED formats
  genotypes: "data/genotypes.vcf"
  
  # Covariates file (tab-separated)
  covariates: "data/covariates.txt"
  
  # Annotation file (BED format)
  annotations: "data/annotations.bed"
  
  # Phenotype files
  expression: "data/expression.txt"
  protein: "data/protein.txt"
  splicing: "data/splicing.txt"

# Large dataset configuration
large_data:
  min_memory_gb: 16
  min_disk_gb: 50
  command_timeout: 7200
  process_by_chromosome: true
  force_plink: true
  monitor_resources: true
  cache_intermediate: true

# Normalization configuration per QTL type
normalization:
  # eQTL normalization options
  eqtl:
    method: "vst"  # "vst", "log2", "quantile", "tpm", "raw"
    vst_blind: true
    fit_type: "parametric"
    use_deseq2: true
    
  # pQTL normalization options  
  pqtl:
    method: "log2"  # "log2", "quantile", "zscore", "raw"
    log2_pseudocount: 1
    remove_zeros: true
    
  # sQTL normalization options
  sqtl:
    method: "log2"  # "log2", "arcsinh", "zscore", "raw"
    log2_pseudocount: 1
    psi_range: [0, 1]  # PSI values range
    
  # Global normalization settings
  global:
    remove_constant_features: true
    constant_threshold: 0.95
    missing_value_threshold: 0.2

# Genotype pre-processing configuration
genotype_processing:
  # Basic processing
  auto_detect_format: true
  output_format: "vcf.gz"
  
  # Reference genome configuration
  reference_genome: ""  # Path to reference genome FASTA file
  reference_genome_index: ""  # Path to reference genome index (.fai)
  
  # Chromosome naming normalization
  normalize_chromosomes: true
  chromosome_prefix: "auto"  # "chr", "none", "auto"
  
  # Variant filtering
  filter_variants: true
  min_maf: 0.01
  min_call_rate: 0.95
  max_missing: 0.1
  quality_threshold: 30
  
  # Multi-allelic site handling
  handle_multiallelic: true
  multiallelic_action: "split"  # "split", "drop", "first_alt"
  
  # Advanced normalization options (require reference genome)
  normalize_indels: false  # Requires reference genome
  remove_duplicates: true
  left_align_variants: false  # Requires reference genome
  
  # Other processing options
  remove_phasing: true
  match_samples: true
  sample_matching_method: "exact"
  
  # QTLtools-specific optimizations
  prefer_plink: true  # Use PLINK format for better performance with QTLtools

# Analysis configuration
analysis:
  # QTL analysis types
  qtl_types: "all"  # "all", "eqtl", "pqtl", "sqtl" or comma-separated list
  
  # QTL mapping mode
  qtl_mode: "cis"  # "cis", "trans", "both"
  
  # GWAS analysis
  run_gwas: false
  gwas_phenotype: "data/gwas_phenotype.txt"

# QTLtools-specific analysis parameters
qtl:
  # QTLtools cis-window size
  cis_window: 1000000
  
  # Trans analysis parameters
  trans_chunk_size: 100
  trans_window: 5000000
  
  # Statistical parameters
  permutations: 1000
  maf_threshold: 0.05
  fdr_threshold: 0.05
  min_maf: 0.01
  min_call_rate: 0.95
  
  # QTLtools performance tuning
  chunk_size: 100
  num_permutations: 1000
  run_nominal: true
  run_permutations: true
  
  # QTLtools specific options
  normal: true  # Use normal approximation for permutations
  bootstrap: false  # Use bootstrap instead of permutations
  seed: 12345  # Random seed for reproducibility
  group: "genes"  # Group by genes for FDR correction
  
  # Conditional analysis
  run_conditional: false
  conditional_method: "nominal"  # "nominal", "permutation"
  
  # Interaction analysis via QTLtools
  run_interaction: false
  interaction_covariate: ""  # Specific covariate for interaction

# GWAS analysis parameters (only used if analysis.run_gwas is true)
gwas:
  method: "linear"  # "linear", "logistic"
  covariates: true
  maf_threshold: 0.01
  imputation: "mean"  # "mean", "median", "drop"

# Enhanced QC configuration with QTLtools compatibility
enhanced_qc:
  enable: true
  generate_normalization_plots: true 
  sample_missingness_threshold: 0.1
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6
  maf_threshold: 0.01
  run_pca: true
  num_pcs: 10
  batch_effect_correction: true
  expression_normalization: true
  outlier_detection: true
  
  # QTLtools PCA options
  pca_covariates: true  # Include PCs as covariates
  num_pc_covariates: 5  # Number of PCs to include as covariates

# Interaction analysis using QTLtools
interaction_analysis:
  enable: false
  interaction_covariates: ["age", "sex", "bmi"]
  fdr_threshold: 0.1
  method: "nominal"  # QTLtools method: "nominal", "permutation"
  window: 1000000  # Window for interaction analysis

# Fine-mapping configuration
fine_mapping:
  enable: false
  method: "susie"  # "susie", "finemap"
  credible_set_threshold: 0.95
  max_causal_variants: 5

# Paths to tools (use default if in PATH)
paths:
  qtltools: "QTLtools"
  bcftools: "bcftools"
  bgzip: "bgzip"
  tabix: "tabix"
  python: "python3"
  plink: "plink"
  R: "R"
  r_script_deseq2: "scripts/utils/deseq2_vst.R"

# Plotting configuration
plotting:
  enabled: true
  dpi: 300
  format: "png"
  style: "seaborn"
  
  # Color scheme
  colors:
    primary: "#2E86AB"
    secondary: "#A23B72"
    significant: "#F18F01"
    nonsignificant: "#C5C5C5"
  
  # Plot types
  plot_types:
    - "manhattan"
    - "qq"
    - "volcano"
    - "distribution"
    - "summary"
    - "locuszoom"
    - "heatmap"

# Output settings
output:
  compression: true
  remove_intermediate: false
  generate_report: true
  report_format: "html"
  save_plots: true
  create_summary: true
  interactive_reports: true
  generate_methods_section: true
  
  # QTLtools output options
  save_nominal: true
  save_permutations: true
  save_interactions: false
  save_conditional: false

# Quality control settings
qc:
  check_sample_concordance: true
  filter_low_expressed: true
  expression_threshold: 0.1
  normalize: true
  check_maf_distribution: true
  check_missingness: true
  
  # Sample QC
  sample_missingness_threshold: 0.1
  sample_heterozygosity_threshold: 3
  
  # Variant QC
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6

# Performance settings optimized for QTLtools
performance:
  num_threads: 8
  memory_gb: 32
  temp_dir: "temp"
  cleanup_temp: true
  parallel_processing: true
  chunk_size: 1000
  
  # QTLtools-specific performance
  qtltools_threads: 4
  qtltools_memory: "16G"
  split_by_chromosome: true

# Advanced settings (for experienced users)
advanced:
  debug_mode: false
  save_logs: true
  validate_outputs: true
  strict_mode: true
  benchmark: true
  
  # QTLtools advanced options
  qtltools_debug: false
  dry_run: false
  resume: false  # Resume from previous run