# Optimized Input Build Configuration for tensorQTL
input_files:
  count_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/Datasets/TRANSCRIPTOMICS_ENABLE300/FULL/Count/count_transcriptomics_300.csv"
  meta_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/Datasets/TRANSCRIPTOMICS_ENABLE300/FULL/Clinical/meta_transcriptomics_300.csv"
  pca_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/pca_result_cohort.eigenvec"
  vcf_input: "/home/ubuntu/DATA_DRIVE/qtl_analysis/ENABL_merged_280_cohort.snp.recalibrated.vcf.gz"
  gtf_table: "/home/ubuntu/DATA_DRIVE/qtl_analysis/gencode.v38.annotation.gtf.full.table.txt"

  count_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/Datasets/TRANSCRIPTOMICS_ENABLE300/FULL/Count/count_transcriptomics_300.csv"
  count_file_sep: ","  # Specify comma for CSV, tab for TSV
  meta_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/Datasets/TRANSCRIPTOMICS_ENABLE300/FULL/Clinical/meta_transcriptomics_300.csv"
  meta_file_sep: ","   # Specify comma for CSV, tab for TSV
  pca_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/pca_result_cohort.eigenvec"
  pca_file_sep: " "    # Usually space for PCA files
  vcf_input: "/home/ubuntu/DATA_DRIVE/qtl_analysis/ENABL_merged_280_cohort.snp.recalibrated.vcf.gz"
  gtf_table: "/home/ubuntu/DATA_DRIVE/qtl_analysis/gencode.v38.annotation.gtf.full.table.txt"
  gtf_table_sep: "\t"  # Usually tab for GTF files

output:
  output_dir: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data"

metadata_columns:
  rnaseq_library: "RNASeq_Library"
  wgs_library: "WGS_Library"

covariates:
  include: ["Age", "Sex", "RNASeq_RIN", "RNASeq_Batch"]
  pca_include: ["PC1", "PC2", "PC3", "PC4", "PC5"]
  pca_count: 5

phenotypes:
  include: ["Age", "Sex", "BMI"]

vcf_processing:
  regions: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10",
            "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19",
            "chr20", "chr21", "chr22"]
  biallelic_only: true
  variant_type: "snps"
  threads: 8
  memory: 8000

annotations:
  feature_type: "gene"
  gene_types: ["protein_coding"]
  additional_columns: ["gene_name", "gene_type"]