# Input Build Configuration for tensorQTL Pipeline
# ================================================

# Input file paths
input_files:
  count_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/Merge_Pre_EMULSION_ENABL150_ENABL300_count_protein_coding.tsv"
  meta_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/meta_wgs_rnaseq.csv"
  pca_file: "/home/ubuntu/DATA_DRIVE/qtl_analysis/pca_result_cohort.eigenvec"
  vcf_input: "/home/ubuntu/DATA_DRIVE/qtl_analysis/ENABL_merged_280_cohort.snp.recalibrated.vcf.gz"
  gtf_table: "/home/ubuntu/DATA_DRIVE/qtl_analysis/gencode.v38.annotation.gtf.full.table.txt"

# Output directory
output:
  output_dir: "/home/ubuntu/DATA_DRIVE/qtl_analysis/input_data"

# Metadata column mappings
metadata_columns:
  rnaseq_library: "RNASeq_Library"
  wgs_library: "WGS_Library"
  age: "Age"
  sex: "Sex" 
  rin: "RNASeq_RIN"
  batch: "RNASeq_Batch"

# Expression data processing
expression_processing:
  remove_zero_genes: true
  expression_threshold: 0.1
  normalization: "none"

# Covariate configuration
covariates:
  include: ["Age", "Sex", "RNASeq_RIN", "RNASeq_Batch"]
  pca_include: ["PC1", "PC2", "PC3", "PC4", "PC5"]
  categorical_columns: ["Sex", "RNASeq_Batch"]
  pca_count: 5
  add_intercept: true
  missing_value_strategy: "drop"

# Phenotype configuration
phenotypes:
  include: ["Age", "Sex", "BMI"]
  categorical_phenotypes: ["Sex"]
  missing_value_strategy: "drop"
  normalization: "standardize"

# VCF processing configuration
vcf_processing:
  regions: ["chr1", "chr2", "chr3", "chr4", "chr5", "chr6", "chr7", "chr8", "chr9", "chr10",
            "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", "chr17", "chr18", "chr19",
            "chr20", "chr21", "chr22"]
  biallelic_only: true
  variant_type: "snps"
  min_quality: 30
  convert_to_plink: true
  
  plink_settings:
    memory: 4000
    threads: 2
    maf_threshold: 0.01
    geno_threshold: 0.1
    mind_threshold: 0.1

# Annotation BED configuration
annotations:
  feature_type: "gene"
  gene_types: ["protein_coding"]
  additional_columns: ["gene_name", "gene_type"]