# Configuration for multi-omics QTL analysis
results_dir: "multi_omics_results"

input_files:
  genotypes: "data/genotypes.vcf.gz"
  covariates: "data/covariates.txt"
  annotations: "data/annotations.bed"
  expression: "data/expression.txt"
  protein: "data/protein.txt"
  splicing: "data/splicing.txt"

genotype_processing:
  normalize_chromosomes: true
  filter_variants: true
  min_maf: 0.01

analysis:
  qtl_types: "all"          # Run all QTL types
  run_gwas: true
  gwas_phenotype: "data/complex_traits.txt"

qtl:
  cis_window: 1000000
  permutations: 1000
  fdr_threshold: 0.05

plotting:
  enabled: true
  plot_types:
    - "manhattan"
    - "qq"
    - "summary"            # Important for comparing across omics types

output:
  generate_report: true
  report_format: "html"