# QTL Analysis Pipeline Configuration for Shell Script
# Optimized for command-line usage with shell script
# ==================================================

# MANDATORY: Results directory (can be overridden by -o option)
results_dir: "results"

# MANDATORY: Input files section
# Note: Data files should be in the directory specified by -d option
input_files:
  # Genotype file - supports VCF, VCF.GZ, BCF, PLINK BED formats
  genotypes: "data/genotypes.vcf.gz"
  
  # Covariates file (tab-separated)
  covariates: "data/covariates.txt"
  
  # Annotation file (BED format)
  annotations: "data/annotations.bed"
  
  # Phenotype files (optional - only required for analyses you run)
  expression: "data/expression.txt"
  protein: "data/protein.txt"
  splicing: "data/splicing.txt"

# Genotype pre-processing configuration
genotype_processing:
  # Reference genome configuration (optional)
  # Uncomment and provide path to enable advanced features
  # reference_genome: ""  # e.g., "reference/hg38.fa"
  # reference_genome_index: ""  # e.g., "reference/hg38.fa.fai"
  
  # Basic processing
  auto_detect_format: true
  output_format: "vcf.gz"
  
  # Chromosome naming normalization
  normalize_chromosomes: true
  chromosome_prefix: "auto"  # "chr", "none", "auto"
  
  # Variant filtering (recommended for quality control)
  filter_variants: true
  min_maf: 0.01
  min_call_rate: 0.95
  max_missing: 0.1
  quality_threshold: 30
  
  # Multi-allelic site handling
  handle_multiallelic: true
  multiallelic_action: "split"  # "split", "drop", "first_alt"
  
  # Advanced normalization options (require reference genome)
  normalize_indels: false  # Requires reference genome
  remove_duplicates: true
  left_align_variants: false  # Requires reference genome
  
  # Other processing options
  remove_phasing: true
  match_samples: true
  sample_matching_method: "exact"

# Analysis configuration
# These can be overridden by command-line options
analysis:
  # QTL types to run (can be overridden by -a option)
  qtl_types: "all"  # "all", "eqtl", "pqtl", "sqtl" or comma-separated list
  
  # QTL mapping mode (can be overridden by -m option)
  qtl_mode: "cis"  # "cis", "trans", "both"
  
  # GWAS analysis (can be overridden by -g option)
  run_gwas: false
  gwas_phenotype: "data/gwas_phenotype.txt"

# QTL analysis parameters
qtl:
  # Cis-window size for cis-QTL analysis
  cis_window: 1000000  # 1 Mb window
  
  # Trans analysis parameters
  trans_window: 5000000  # 5 Mb window for trans-QTL
  
  # Statistical parameters
  permutations: 1000
  maf_threshold: 0.05
  fdr_threshold: 0.05
  min_maf: 0.01
  min_call_rate: 0.95

# GWAS analysis parameters (only used if analysis.run_gwas is true)
gwas:
  method: "linear"  # "linear", "logistic"
  covariates: true
  maf_threshold: 0.01
  imputation: "mean"  # "mean", "median", "drop"

# Paths to tools (use default if in PATH)
paths:
  qtltools: "qtltools"
  bcftools: "bcftools"
  bgzip: "bgzip"
  tabix: "tabix"
  python: "python3"
  plink: "plink"
  R: "R"

# Plotting configuration
plotting:
  enabled: true
  dpi: 300
  format: "png"
  style: "seaborn"
  
  # Color scheme for plots
  colors:
    primary: "#2E86AB"
    secondary: "#A23B72"
    significant: "#F18F01"
    nonsignificant: "#C5C5C5"
  
  # Plot types to generate
  plot_types:
    - "manhattan"
    - "qq"
    - "volcano"
    - "distribution"
    - "summary"

# Output settings
output:
  compression: true
  remove_intermediate: false
  generate_report: true
  report_format: "html"
  save_plots: true
  create_summary: true

# Quality control settings
qc:
  check_sample_concordance: true
  filter_low_expressed: true
  expression_threshold: 0.1
  normalize: true
  check_maf_distribution: true
  check_missingness: true
  
  # Sample QC
  sample_missingness_threshold: 0.1
  sample_heterozygosity_threshold: 3
  
  # Variant QC
  variant_missingness_threshold: 0.1
  hwe_threshold: 1e-6

# Performance settings
performance:
  num_threads: 4
  memory_gb: 8
  temp_dir: "temp"
  cleanup_temp: true

# Advanced settings
advanced:
  debug_mode: false
  save_logs: true
  validate_outputs: true
  strict_mode: true