# Configuration for PLINK BED format genotypes
results_dir: "plink_analysis_results"

input_files:
  genotypes: "data/plink_data.bed"  # With corresponding .bim and .fam files
  covariates: "data/covariates.txt"
  annotations: "data/annotations.bed"
  expression: "data/expression.txt"

# PLINK format automatically converted to VCF
genotype_processing:
  auto_detect_format: true
  normalize_chromosomes: true
  chromosome_prefix: "none"  # PLINK typically uses "1" not "chr1"
  filter_variants: true
  min_maf: 0.01
  min_call_rate: 0.95

analysis:
  qtl_types: "eqtl"
  run_gwas: true
  gwas_phenotype: "data/gwas_phenotypes.txt"

gwas:
  method: "linear"
  covariates: true