# MANDATORY: Results directory where all output will be stored
results_dir: "/Users/singhvj/QTL_ANALYSIS_OUTPUT/results"

# MANDATORY: Input files section
input_files:
  # Genotype file - supports VCF, VCF.GZ, BCF, PLINK BED formats
  genotypes: "/Users/singhvj/QTL_ANALYSIS_OUTPUT/genotypes.vcf.gz"
  # Covariates file (tab-separated)
  covariates: "/Users/singhvj/QTL_ANALYSIS_OUTPUT/covariates.txt"
  # Annotation file (BED format)
  annotations: "/Users/singhvj/QTL_ANALYSIS_OUTPUT/annotations.bed"
  # Phenotype files
  expression: "/Users/singhvj/QTL_ANALYSIS_OUTPUT/expression.tsv"
  protein: ""
  splicing: ""

paths:
  plink2: "plink2"  # or full path if not in PATH
  plink: "plink"    # or full path if not in PATH
  plink1.9: "plink1.9"  # optional


analysis:
  qtl_types: ["eqtl"]  # or ["eqtl", "pqtl", "sqtl"] or "all"
  qtl_mode: "cis"  # "cis", "trans", or "both"

# Enhanced tensorQTL configuration
tensorqtl:
  use_gpu: true  # Set to false if you want to force CPU
  output_format: "parquet"  # "parquet" or "tsv"
  batch_size: 20000  # Default batch size for processing
  
  # Enhanced cis-QTL settings
  cis_window: 1000000  # Window size for cis-QTL (1Mb)
  seed: 123456  # Random seed for reproducibility
  fdr_threshold: 0.05  # FDR threshold for significant associations
  
  # New: Enable nominal mapping (all variant-phenotype pairs)
  run_nominal: true
  
  # Enhanced trans-QTL settings
  trans:
    pval_threshold: 1e-5  # Only return associations with p-value <= this threshold
    maf_threshold: 0.05   # MAF threshold for variants in trans analysis
    batch_size: 10000     # Batch size for trans analysis
    cis_window: 5000000   # Window for filtering cis associations (5Mb)

# Enhanced genotype processing
genotype_processing:
  maf_threshold: 0.01      # Minor allele frequency
  call_rate_threshold: 0.95 # SNP call rate
  hwe_threshold: 1e-6      # Hardy-Weinberg equilibrium p-value threshold
  plink_threads: 4         # Number of threads for PLINK operations

# Enhanced QC settings
qc:
  normalize: true
  filter_lowly_expressed_genes: true
  low_expression_threshold: 0.1
  max_lowly_expressed_samples_percentage: 10
  constant_threshold: 0.95
  missing_value_threshold: 0.2

# Enhanced normalization settings
normalization:
  eqtl:
    method: "vst"  # "log2", "vst", "quantile", "zscore", "arcsinh", "tpm"
    log2_pseudocount: 1
    arcsinh_cofactor: 1
  pqtl:
    method: "log2"
    log2_pseudocount: 1
  sqtl:
    method: "log2"
    log2_pseudocount: 1

# Enhanced data handling
data_handling:
  missing_value_threshold: 0.2

# Enhanced pipeline options
enhanced_pipeline:
  enable: true

enhanced_qc:
  generate_enhanced_covariates: true
  generate_normalization_plots: true

# Batch correction (if available)
batch_correction:
  enabled:
    eqtl: true
    pqtl: false
    sqtl: false
  exp_covariate_design: "path/to/exp_covariate_design.txt"  # Optional

# Performance optimization
performance:
  num_threads: 8  # Number of CPU threads to use

# Large data handling
large_data:
  command_timeout: 7200  # Timeout for long-running commands in seconds