# Test Configuration for NAFLD QTL Analysis Pipeline
# This configuration uses the sample data provided

results_dir: "test_results"

# Input files
input_files:
  genotypes: "data/genotypes.vcf"
  covariates: "data/covariates.txt"
  annotations: "data/annotations.bed"
  expression: "data/expression.txt"
  protein: "data/protein.txt"
  splicing: "data/splicing.txt"
  # gwas_phenotype: "data/gwas_phenotype.txt"  # Commented out since PLINK is missing

# Genotype processing (optimized for test data)
genotype_processing:
  # Basic processing
  auto_detect_format: true
  output_format: "vcf.gz"
  
  # Chromosome naming
  normalize_chromosomes: true
  chromosome_prefix: "chr"
  
  # Variant filtering (relaxed for test data)
  filter_variants: true
  min_maf: 0.1
  min_call_rate: 0.8
  max_missing: 0.2
  quality_threshold: 20
  
  # Multi-allelic sites
  handle_multiallelic: true
  multiallelic_action: "split"
  
  # Advanced options (disabled for test)
  normalize_indels: false
  remove_duplicates: true
  left_align_variants: false
  
  # Other options
  remove_phasing: true
  match_samples: true
  sample_matching_method: "exact"

# Analysis configuration
analysis:
  qtl_types: "all"  # Test all QTL types
  qtl_mode: "cis"   # Test cis-QTL only for speed
  run_gwas: false   # Disabled since PLINK is missing

# QTL parameters (optimized for test data)
qtl:
  cis_window: 500000  # Smaller window for test data
  permutations: 100   # Fewer permutations for testing
  maf_threshold: 0.1
  fdr_threshold: 0.1  # Relaxed threshold for testing
  min_maf: 0.1
  min_call_rate: 0.8

# Tool paths
paths:
  qtltools: "qtltools"
  bcftools: "bcftools"
  bgzip: "bgzip"
  tabix: "tabix"
  python: "python3"
  # plink: "plink"  # Commented out since not available

# Plotting configuration
plotting:
  enabled: true
  dpi: 150  # Lower DPI for testing
  format: "png"
  style: "seaborn"
  plot_types:
    - "manhattan"
    - "qq"
    - "summary"

# Output settings
output:
  compression: false  # Disable compression for easier debugging
  remove_intermediate: false
  generate_report: true
  report_format: "html"

# Quality control
qc:
  check_sample_concordance: true
  filter_low_expressed: true
  expression_threshold: 0.05
  normalize: true

# Performance settings (optimized for testing)
performance:
  num_threads: 2
  memory_gb: 4
  temp_dir: "temp"
  cleanup_temp: false

# Advanced settings
advanced:
  debug_mode: true  # Enable debug for testing
  save_logs: true
  validate_outputs: true
  strict_mode: false  # Relaxed for testing